-
    name: 'get current date/time'
    command: date
    register: ws_date
    tags: ws_date    
- 
    name: Send Emails to a bunch of users, with Playbook Report as an attachment.
    mail:
      host: pmta.hchgrp.com
      port: 25
      subject: WFB {{ deploy_type }} of version {{ version }} Synchronization is complete
      body: WFB {{ deploy_type }} of version {{ version }} Synchronization is complete at `{{ ws_date.stdout }}`
      from: wfb@vericast.com 
      to:
      - george.arellano@harlandclarke.com
      - avinash.desham@vericast.com      
      cc: middleware@harlandclarke.com
      headers:
      - Reply-To=middleware@harlandclarke.com
      - X-Special="This is to confirm the Syncronization of changes is complete"
      charset: us-ascii
    delegate_to: '{{ inventory_hostname }}'