---
#file: roles/was_deploy/defaults/main.yaml
wsadmin_path: /usr/local/WebSphere7/AppServer/profiles/Dmgr01/bin/wsadmin.sh
app_install: /usr/local/scripts/Automated-RC_Scheduler-Jython-Install
app_name: "'RC_Scheduler'"

slack_token: "T8XFBCPUJ/BB5EN658B/N8kt3TJtki8GeedVvdcfRX45"
slack_host: localhost