-
    name: 'get current date/time'
    command: date
    register: ws_date
    tags: ws_date
-
    name: 'sending message to slack channel'
    import_role:
        name: slack
    vars:
        payload: '*** copying jsp file before starting the deployment'
    tags: slack
-
    name: 'jsp file copy'
    shell: '{{ jsp_copy_path }}'
    register: jsp_copy_out
-
    name: 'copy script output'
    debug:
        msg: '{{ jsp_copy_out.stdout_lines }}'
-
    name: 'sending message to slack channel'
    import_role:
        name: slack
    vars:
        payload: "*** Completed this task ***{{ jsp_copy_out.stdout }} "
    tags: slack
