---
#file: roles/docker_pull/tasks/main.yaml
- name: get current date/time
  command: date
  register: ws_date
  tags: ws_date

- name: Log into private registry and force re-authorization
  docker_login:
    registry: '{{registry_name}}'
    username: '{{user}}'
    password: '{{pass}}'
    reauthorize: yes

- name: pull image from github docker repo
  docker_image:
    name: '{{image_name}}'
    repository: '{{repository_url}}'
    tag: '{{tag_name}}'
    pull: yes

- name: sending message to slack channel
  import_role:
    name: slack
  vars:
    payload: |
          Completed pulling the image `{{repository_url}}/{{image_name}}:{{tag_name}}` on    `{{ inventory_hostname }}`
    clr: good
  tags: slack
