
- name: stop message
  hosts: all
  become: yes
  gather_facts: no

  tasks:

    - name: get current date/time
      command: date
      register: cur_date
      tags: cur_date

    - name: slack completed modifying resource
      import_role:
        name: slack
      vars:
        payload: |
         ************#########################*************
         Completed deployment of current workflow at:
             `{{ cur_date.stdout }}`
         ************#########################*************
        clr: good
      tags: slack,skip
