---
#file: pip_install.yaml
- hosts: all
  tasks:
  - name: download
    command: "{{ item }}"
    with_items:
      - bash
      - export https_proxy="http://gateway.zscalertwo.net:80"
      - /root/install_pip.sh
    register: command_result
