---
#file: pip_install.yaml
- name: download
  hosts: all
  gather_facts: false
- command: "{{item}}"
  with_items:
  - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
  - python get-pip.py
  - pip install docker.py
