---
#file: rc_sch_deply.yaml
- name: RC Scheduler update deployment role
  hosts: all
  gather_facts: false
  roles:
    - copy_ear
    - was_uninstall
    - config_save
    - was_sync
    - was_deply
    - config_save
    - was_sync
