---
#file: rc_sch_deply.yaml
- name: RC Scheduler update deployment role
  hosts: all
  gather_facts: false
  roles:
    - copy_ear
    # - was_uninstall
    # - config_save_v9
    # - was_sync
    - was_deply_v9
