---
- name: slack notification test
  hosts: all
  gather_facts: false
  become: yes
  become_user: root
  tasks:
    - name: import slack role
      import_role:
        name: slack
      vars:
        payload: "test notification from {{ inventory_hostname }}"
      tags: slack, tower