-
    name: 'get current date/time'
    command: date
    register: ws_date
    tags: ws_date
-
    name: 'sending message to slack channel'
    import_role:
        name: slack
    vars:
        payload: '*** Flipping {{ appname }} on {{ inventory_hostname }} to cluster {{cluster_name}} {{ ws_date.stdout }}...'
    tags: slack
-
    name: 'flip cluster'
    shell: '{{ flip_script_path }}'

-
    name: 'sending message to slack channel'
    import_role:
        name: slack
    vars:
        payload: "{{appname}} has been flipped to cluster {{cluster_name}}"
    tags: slack
