---
#file: roles/was_sync/tasks/main.yaml
- name: get current date/time
  command: date
  register: ws_date
  tags: ws_date

- name: sending message to slack channel
  import_role:
    name: slack
  vars:
    payload: "*** Starting was sync at {{ ws_date.stdout }} on {{ inventory_hostname }}..."
  tags: slack

- name: sync active nodes
  shell: '{{ wsadmin_path }} -lang jython -c "{{ ws_sync }}"'
  register: was_sync_out
  tags: was_sync

- name: sync output
  debug:
    msg: "{{ was_sync_out.stdout_lines }}"
  tags: was_out

- name: sending message to slack channel
  import_role:
    name: slack
  vars:
    payload: "*** Completed was sync on {{ inventory_hostname }}:\n {{ was_sync_out.stdout }}"
    clr: warning
  tags: slack
