---
- name: sync active nodes
  shell: '{{ wsadmin_path }} -lang jython -c "{{ ws_sync }}"'
  register: was_sync_out
  tags: was_sync

- name: sync output
  debug:
    msg: "{{ was_sync_out.stdout_lines }}"
  tags: was_out

- name: sending message to slack channel
  slack:
    token: "{{ slack_token }}"
    msg: "was sync output: {{ was_sync_out.stdout }}"
    color: good
  delegate_to: localhost
  tags: slack