---
  - name: sync active nodes
    shell: '{{ wsadmin_path }} -conntype none -lang jython -c "{{ app_list }}"'
    register: was_sync_out

  - name: sync output
    debug:
      msg: "{{ was_sync_out.stdout_lines }}"