-
    name: 'get current date/time'
    command: date
    register: ws_date
    tags: ws_date
-
    name: 'sending message to slack channel'
    import_role:
        name: slack
    vars:
        payload: '*** extracting latest pep tar file'
    tags: slack
-
    name: 'pep tar extract'
    shell: '{{ pep_tar_script }}'
    register: pep_tar_out
-
    name: 'pep tar script output'
    debug:
        msg: '{{ pep_tar_out.stdout_lines }}'
-
    name: 'sending message to slack channel'
    import_role:
        name: slack
    vars:
        payload: "*** Completed this task ***{{ pep_tar_out.stdout }} "
    tags: slack
