---
#file: roles/was_uninstall/tasks/main.yaml
- name: get current date/time
  command: date
  register: ws_date
  tags: ws_date

- name: sending message to slack channel
  import_role:
    name: slack
  vars:
    payload: "*** Starting deployment of {{ app_name }} app deployment at {{ ws_date.stdout }} on {{ inventory_hostname }}..."
  tags: slack

- name: uninstall app
  shell: '{{ wsadmin_path }} -lang jython -c "{{ uninstall_app }}"'
  register: uninstall_out
  tags: unisnt

- name: uninstall output
  debug:
    msg: "{{ uninstall_out.stdout_lines }}"
  tags: uninst_out

- name: sending message to slack channel
  import_role:
     name: slack
  vars:
    payload: "*** Completed uninstalling {{ app_name }} on {{ inventory_hostname }}:\n {{ uninstall_out.stdout }}"
    clr: danger
  tags: slack
