---
#file: roles/list_apps/tasks/main.yaml
- name: query apps
  shell: '{{ wsadmin_path }} -lang jython -f "{{ ws_script }}"'
  register: ws_out
  tags: query_apps

- name: apps list
  debug:
    msg: "{{ ws_out.stdout_lines }}"
  tags: list_apps

- name: debug slack role
  import_role:
    name: slack
  vars:
    payload: "*** Applications currently running on {{ inventory_hostname }}  -- {{ wsadmin_path }}:\n {{ ws_out.stdout }}"
  tags: slackr
