---
- name: Sending message to slack channel
  slack:
    token: "{{ item }}"
    msg: "{{ payload }}"
    color: "{{ clr }}"
    validate_certs: no
  delegate_to: "{{ slack_host }}"
  ignore_errors: yes
  with_items: "{{ tokens }}"
