---
#file: roles/was_uninstall/defaults/main.yaml
wsadmin_path: /usr/local/WebSphere7/AppServer/profiles/Dmgr01/bin/wsadmin.sh
uninstall_app: 'AdminApp.uninstall({{ app_name }})'
app_name: "'RC_Scheduler'"

slack_token: "T8XFBCPUJ/BB5EN658B/N8kt3TJtki8GeedVvdcfRX45"
slack_host: sa1x-awx-p1