---
    registry_name: docker.pkg.github.com
    user: avinashdesham
    pass: d7a9efde0a45ae0bf0df78019c22af607e8de33d
    image_name: docker.pkg.github.com/harlandclarke/hc-cs-unified-order-entry-integration/hc-integration:qa
  #  repository_url: docker.pkg.github.com/harlandclarke/hc-cs-unified-order-entry-ui/
  #  tag_name: qa
