---
- name: query apps
  shell: '{{ wsadmin_path }} -conntype none -lang jython -c "{{ app_list }}"'
  register: apps_out

- name: apps list
  debug:
    msg: "{{ apps_out.stdout_lines }}"

- name: Sending message to slack channel
  slack:
    token: "{{ slk_token }}"
    msg: "running apps on {{ inventory_hostname }}: {{ apps_out.stdout_lines }}"
  delegate_to: localhost
  tags: slack