-
    name: 'get current date/time'
    command: date
    register: ws_date
    tags: ws_date

-   
    name: Move tar to archive
    shell: 'mv {{ text_path }}/{{ deploy_type }}-{{ version }}-pre.tar.gz {{ archive_path }}/{{ deploy_type }}-{{ version }}-pre.tar.gz'


-
    name: 'sending message to slack channel'
    import_role:
        name: slack
    vars:
        payload: "*** Completed archiving of  {{ deploy_type }}-{{ version }}-pre.tar.gz "
        clr: good
    tags: slack


-   
    name: Move txt to archive
    shell: 'mv {{ text_path }}/{{ deploy_type }}-{{ version }}-pre.txt {{ archive_path }}/{{ deploy_type }}-{{ version }}-pre.txt'


-
    name: 'sending message to slack channel'
    import_role:
        name: slack
    vars:
        payload: "*** Completed archiving of  {{ deploy_type }}-{{ version }}-pre.txt "
        clr: good
    tags: slack


-   
    name: remove dir from deployment
    shell: 'rm -rf {{ text_path }}/{{ deploy_type }}-{{ version }}-pre'


-
    name: 'sending message to slack channel'
    import_role:
        name: slack
    vars:
        payload: "*** Completed removal of  {{ deploy_type }}-{{ version }}-pre from deployment directory"
        clr: good
    tags: slack    
