- name: test command
  command: echo -n "foo"

- name: create tmp dir
  file:
    path: /tmp/ci_pipeline/
    state: directory

- name: Download file with custom HTTP headers
  get_url:
    url: https://www.gitlab.com/api/v4/projects/25427711/jobs/1586488246/artifacts
    dest: /tmp/ci_pipeline/artifacts.zip
    validate_certs: no
    headers:
      PRIVATE-TOKEN: "{{ token }}"


- name: cleanup tmp dir
  file:
    path: /tmp/ci_pipeline/
    state: absent