- name: test command
  command: echo -n "foo"

- name: create tmp dir
  file:
    path: /tmp/ci_pipeline/
    state: directory

- name: Download file with custom HTTP headers
  get_url:
    url: gitlab.com/api/v4/projects/25427711/jobs/1586488246/artifacts
    dest: /tmp/ci_pipeline/artifacts.zip
    headers:
      PRIVATE-TOKEN: "{{ faketoken }}"


- name: cleanup tmp dir
  ansible.builtin.file:
    path: /tmp/ci_pipeline/
    state: absent