- name: create tmp dir
  file:
    path: /tmp/ci_pipeline/
    state: directory

- name: Download file with custom HTTP headers
  command: curl --location --header "PRIVATE-TOKEN: '{{ token }}'" "gitlab.com/api/v4/projects/25427711/jobs/1586488246/artifacts" --output artifacts.zip

- name: cleanup tmp dir
  file:
    path: /tmp/ci_pipeline/
    state: absent