---
- name: create tmp dir
  command: mkdir /tmp/ci_pipeline/

- name: Download file with custom HTTP headers
  command: curl --location --header  "{{ token|quote }}" "gitlab.com/api/v4/projects/25427711/jobs/1586488246/artifacts" --output artifacts.zip

- name: cleanup tmp dir
  command: rm -rf  /tmp/ci_pipeline/